### ISSUE TITLE
Automatic Reboot in Node-Red

### ISSUE THREAD

**Issue by belveder79** [btsimonh/826-x-ip-camera#6]
just came across this amazing stuff... my Yatwin is also one of those cams with the mipc software...

do you have any idea how to implement the reboot command in node-red?
since i have blocked internet access for mine, it tends to lock up every few days, and rebooting it periodically would be a nice workaround...

**Comment by btsimonh** [comment]
hi, I've not looked at my cam for some time, but assume there is a reboot button on their UI, but that you would need to be 'logged in' to send the appropriate command.
The approach I would take would be to fire up Chrome Dev tools, and visit the cam UI.  Observe network traffic when you press the reset button, and attempt to replicate what it sends.
Then you just have to check my original NR flow for authorization and sending commands works against the firmware you have, and add the reset command to the flow.....
br, simon

**Comment by belveder79** [comment]
hi, thx for the hint - yes, since you did 99% of the work already concerning the authentication, this part is solved already :-)

Exactly as you suggested, I tracked down the reboot button until the point where there is a "do you really want to restart?" popup and to the msg.send(something), even before I ran across your development... so I will try that and post my milage to have you put it into your flow for reference...

best, Clemens

**Comment by belveder79** [comment]
well... that was suuuuper easy, thanks to your implementation:

this one goes into the init function node:

```
    ccm_reboot: function( ){
        var type = 2;
        var newnid = this.makenid(++this.nid_seq, type ? this.lid:0, this.login_secret_dec, type, null, null);
        var data =  {
                sess: 1,
                sess_nid: newnid,
                sess_sn: this.sn
            };
            
        ccm.send_msg(
            "ccm_reboot.js", 
            data
        );
    }
```
and there is just a simple function that does this:
```
var ccm = flow.get('ccm');
ccm.ccm_reboot();
```

works like a charm, thx again...

**Comment by btsimonh** [comment]
I just love people who understand stuff!
To save me working out where all my flows are, etc....  could you do a PR?

**Comment by belveder79** [comment]
:-) Sure… will do asap…

btsimonh ***@***.***> schrieb am Fr. 20. Aug. 2021 um 19:27:

**Comment by btsimonh** [comment]
thankyou again!
